/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

/**
 *
 * @author edgar
 */
public class JFrmGastosPlanificados extends javax.swing.JFrame {

    /**
     * Creates new form MenuPrincipal
     */
    public JFrmGastosPlanificados() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jBtnEliminarGastosPlanificados = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jBtnSumarGastosPlanificados = new javax.swing.JButton();
        jBtnHomeGastosPlanificados = new javax.swing.JButton();
        jTxtResultadoGastosPlanificados = new javax.swing.JTextField();
        jTxtMontoGastosPlanificados = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jTxtMesGastosPlanificados = new javax.swing.JTextField();
        jTxtAnioGastosPlanificados = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jTxtTipoGastosPlanificados = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jBtnEliminarGastosPlanificados.setText("Restar");
        jBtnEliminarGastosPlanificados.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnEliminarGastosPlanificadosActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Arial Black", 0, 18)); // NOI18N
        jLabel2.setText("Gastos Planificados");

        jBtnSumarGastosPlanificados.setText("Sumar");
        jBtnSumarGastosPlanificados.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnSumarGastosPlanificadosActionPerformed(evt);
            }
        });

        jBtnHomeGastosPlanificados.setText("Home");

        jTxtResultadoGastosPlanificados.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTxtResultadoGastosPlanificadosActionPerformed(evt);
            }
        });

        jTxtMontoGastosPlanificados.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTxtMontoGastosPlanificadosActionPerformed(evt);
            }
        });

        jLabel3.setText("Monto del Gasto");

        jTxtMesGastosPlanificados.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTxtMesGastosPlanificadosActionPerformed(evt);
            }
        });

        jTxtAnioGastosPlanificados.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTxtAnioGastosPlanificadosActionPerformed(evt);
            }
        });

        jLabel4.setText("Mes");

        jLabel5.setText("Año");

        jLabel6.setText("Tipo de Gasto");

        jTxtTipoGastosPlanificados.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTxtTipoGastosPlanificadosActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addGap(80, 80, 80))
            .addGroup(layout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addGap(18, 18, 18))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addGap(26, 26, 26)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jTxtMontoGastosPlanificados, javax.swing.GroupLayout.DEFAULT_SIZE, 191, Short.MAX_VALUE)
                            .addComponent(jTxtTipoGastosPlanificados)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5))
                        .addGap(27, 27, 27)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTxtAnioGastosPlanificados, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTxtMesGastosPlanificados, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jBtnHomeGastosPlanificados, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(106, 106, 106))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jBtnSumarGastosPlanificados, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jBtnEliminarGastosPlanificados, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jTxtResultadoGastosPlanificados, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 296, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(60, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(jTxtMesGastosPlanificados, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(38, 38, 38))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel5)
                        .addComponent(jTxtAnioGastosPlanificados, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 20, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jTxtTipoGastosPlanificados, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jTxtMontoGastosPlanificados, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBtnSumarGastosPlanificados)
                    .addComponent(jBtnEliminarGastosPlanificados))
                .addGap(18, 18, 18)
                .addComponent(jTxtResultadoGastosPlanificados, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32)
                .addComponent(jBtnHomeGastosPlanificados)
                .addGap(20, 20, 20))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTxtResultadoGastosPlanificadosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTxtResultadoGastosPlanificadosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTxtResultadoGastosPlanificadosActionPerformed

    private void jTxtMontoGastosPlanificadosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTxtMontoGastosPlanificadosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTxtMontoGastosPlanificadosActionPerformed

    private void jTxtMesGastosPlanificadosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTxtMesGastosPlanificadosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTxtMesGastosPlanificadosActionPerformed

    private void jTxtAnioGastosPlanificadosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTxtAnioGastosPlanificadosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTxtAnioGastosPlanificadosActionPerformed

    private void jTxtTipoGastosPlanificadosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTxtTipoGastosPlanificadosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTxtTipoGastosPlanificadosActionPerformed

    private void jBtnSumarGastosPlanificadosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnSumarGastosPlanificadosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jBtnSumarGastosPlanificadosActionPerformed

    private void jBtnEliminarGastosPlanificadosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnEliminarGastosPlanificadosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jBtnEliminarGastosPlanificadosActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFrmGastosPlanificados.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFrmGastosPlanificados.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFrmGastosPlanificados.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFrmGastosPlanificados.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JFrmGastosPlanificados().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton jBtnEliminarGastosPlanificados;
    public javax.swing.JButton jBtnHomeGastosPlanificados;
    public javax.swing.JButton jBtnSumarGastosPlanificados;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    public javax.swing.JTextField jTxtAnioGastosPlanificados;
    public javax.swing.JTextField jTxtMesGastosPlanificados;
    public javax.swing.JTextField jTxtMontoGastosPlanificados;
    public javax.swing.JTextField jTxtResultadoGastosPlanificados;
    public javax.swing.JTextField jTxtTipoGastosPlanificados;
    // End of variables declaration//GEN-END:variables
}
