/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

/**
 *
 * @author edgar
 */
public class JFrmIngresosPlanificados extends javax.swing.JFrame {

    /**
     * Creates new form MenuPrincipal
     */
    public JFrmIngresosPlanificados() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jBtnEliminarIngresosPlanificados = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jBtnSumarIngresosPlanificados = new javax.swing.JButton();
        jBtnRetrocederIngresosPlanificados = new javax.swing.JButton();
        jBtnHomeIngresosPlanificados = new javax.swing.JButton();
        jBttnAvanzarIngresosPlanificados = new javax.swing.JButton();
        jTxtResultadoIngresos = new javax.swing.JTextField();
        jTxtMontoIngresoIngresosPlanificados = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jTxtMesIngresosPlanificados = new javax.swing.JTextField();
        jTxtAnioIngresosPlanificados = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jTxtTipoIngresoIngresosPlanificados = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jBtnEliminarIngresosPlanificados.setText("Restar");
        jBtnEliminarIngresosPlanificados.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnEliminarIngresosPlanificadosActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Arial Black", 0, 18)); // NOI18N
        jLabel2.setText("Ingresos Planificados");

        jBtnSumarIngresosPlanificados.setText("Sumar");
        jBtnSumarIngresosPlanificados.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnSumarIngresosPlanificadosActionPerformed(evt);
            }
        });

        jBtnRetrocederIngresosPlanificados.setText("Retroceder");

        jBtnHomeIngresosPlanificados.setText("Home");

        jBttnAvanzarIngresosPlanificados.setText("Avanzar");

        jTxtResultadoIngresos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTxtResultadoIngresosActionPerformed(evt);
            }
        });

        jTxtMontoIngresoIngresosPlanificados.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTxtMontoIngresoIngresosPlanificadosActionPerformed(evt);
            }
        });

        jLabel3.setText("Monto del Ingreso");

        jTxtMesIngresosPlanificados.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTxtMesIngresosPlanificadosActionPerformed(evt);
            }
        });

        jTxtAnioIngresosPlanificados.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTxtAnioIngresosPlanificadosActionPerformed(evt);
            }
        });

        jLabel4.setText("Mes");

        jLabel5.setText("Año");

        jLabel6.setText("Tipo de Ingreso");

        jTxtTipoIngresoIngresosPlanificados.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTxtTipoIngresoIngresosPlanificadosActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addGap(80, 80, 80))
            .addGroup(layout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addGap(18, 18, 18))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addGap(26, 26, 26)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jTxtMontoIngresoIngresosPlanificados, javax.swing.GroupLayout.DEFAULT_SIZE, 191, Short.MAX_VALUE)
                            .addComponent(jTxtTipoIngresoIngresosPlanificados)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5))
                        .addGap(27, 27, 27)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTxtAnioIngresosPlanificados, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTxtMesIngresosPlanificados, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jBtnRetrocederIngresosPlanificados)
                            .addGap(28, 28, 28)
                            .addComponent(jBtnHomeIngresosPlanificados, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(33, 33, 33)
                            .addComponent(jBttnAvanzarIngresosPlanificados))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jBtnSumarIngresosPlanificados, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jBtnEliminarIngresosPlanificados, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jTxtResultadoIngresos, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 296, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(60, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(jTxtMesIngresosPlanificados, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(38, 38, 38))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel5)
                        .addComponent(jTxtAnioIngresosPlanificados, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 20, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jTxtTipoIngresoIngresosPlanificados, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jTxtMontoIngresoIngresosPlanificados, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBtnSumarIngresosPlanificados)
                    .addComponent(jBtnEliminarIngresosPlanificados))
                .addGap(18, 18, 18)
                .addComponent(jTxtResultadoIngresos, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBtnRetrocederIngresosPlanificados)
                    .addComponent(jBtnHomeIngresosPlanificados)
                    .addComponent(jBttnAvanzarIngresosPlanificados))
                .addGap(20, 20, 20))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTxtResultadoIngresosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTxtResultadoIngresosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTxtResultadoIngresosActionPerformed

    private void jTxtMontoIngresoIngresosPlanificadosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTxtMontoIngresoIngresosPlanificadosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTxtMontoIngresoIngresosPlanificadosActionPerformed

    private void jTxtMesIngresosPlanificadosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTxtMesIngresosPlanificadosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTxtMesIngresosPlanificadosActionPerformed

    private void jTxtAnioIngresosPlanificadosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTxtAnioIngresosPlanificadosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTxtAnioIngresosPlanificadosActionPerformed

    private void jTxtTipoIngresoIngresosPlanificadosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTxtTipoIngresoIngresosPlanificadosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTxtTipoIngresoIngresosPlanificadosActionPerformed

    private void jBtnSumarIngresosPlanificadosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnSumarIngresosPlanificadosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jBtnSumarIngresosPlanificadosActionPerformed

    private void jBtnEliminarIngresosPlanificadosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnEliminarIngresosPlanificadosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jBtnEliminarIngresosPlanificadosActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFrmIngresosPlanificados.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFrmIngresosPlanificados.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFrmIngresosPlanificados.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFrmIngresosPlanificados.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JFrmIngresosPlanificados().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton jBtnEliminarIngresosPlanificados;
    public javax.swing.JButton jBtnHomeIngresosPlanificados;
    public javax.swing.JButton jBtnRetrocederIngresosPlanificados;
    public javax.swing.JButton jBtnSumarIngresosPlanificados;
    public javax.swing.JButton jBttnAvanzarIngresosPlanificados;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    public javax.swing.JTextField jTxtAnioIngresosPlanificados;
    public javax.swing.JTextField jTxtMesIngresosPlanificados;
    public javax.swing.JTextField jTxtMontoIngresoIngresosPlanificados;
    public javax.swing.JTextField jTxtResultadoIngresos;
    public javax.swing.JTextField jTxtTipoIngresoIngresosPlanificados;
    // End of variables declaration//GEN-END:variables
}
